repos:
  # Ruff - 现代化 Python 代码检查和格式化
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        name: Ruff Linting
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^(scripts/|docs/|tests/fixtures/)
      - id: ruff-format
        name: Ruff Formatting
        exclude: ^(scripts/|docs/|tests/fixtures/)

  # 基础代码质量检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML Syntax
      - id: check-added-large-files
        name: Check for Large Files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Check for Merge Conflicts
      - id: check-json
        name: Check JSON Syntax
      - id: check-toml
        name: Check TOML Syntax

  # MyPy 类型检查 (基础配置，避免依赖问题)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        name: MyPy Type Check
        additional_dependencies: [types-requests, types-setuptools]
        exclude: ^(tests/|scripts/|docs/)
        args: [--ignore-missing-imports, --show-error-codes, --no-strict-optional]
