name: bluev-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and build tools
  - python=3.12.3
  - pip
  - setuptools
  - wheel

  # GUI Framework
  - pyside6
  - qt6-main

  # Computer Vision and Image Processing
  - opencv
  - pillow

  # Scientific Computing
  - numpy

  # System dependencies (simplified)
  - openssl
  - sqlite
  - zlib
  - pip:
      # Core application dependencies
      - opencv-python>=4.8.0
      - pyautogui>=0.9.50
      - pynput>=1.8.0
      - pyperclip>=1.9.0
      - pydantic>=2.0.0
      - python-dotenv>=1.0.0
      - sqlalchemy>=2.0.0
      - requests>=2.28.0

      # Development and testing tools
      - pytest>=8.0.0
      - pytest-cov>=4.0.0
      - pytest-mock>=3.10.0
      - pytest-qt>=4.0.0
      - mypy>=1.0.0
      - ruff>=0.1.0
      - pre-commit>=3.0.0
      - coverage>=7.0.0

      # Documentation tools
      - mkdocs>=1.5.0
      - mkdocs-material>=9.0.0
      - mkdocstrings[python]>=0.20.0

      # Build and packaging tools
      - build>=0.10.0
      - tox>=4.0.0
