site_name: BlueV Documentation
site_description: 智能桌面自动化工具 - 现代化的工作流自动化解决方案
site_url: https://guanrya5.github.io/OneDay_BuleV
repo_url: https://github.com/GuanryA5/OneDay_BuleV
repo_name: GuanryA5/OneDay_BuleV

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh
  - mkdocstrings:
      handlers:
        python:
          paths: [bluev]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes

nav:
  - 首页: index.md
  - 项目文档:
    - 项目简介: brief.md
    - 产品需求文档: PRD_v1.0.md
    - 技术实现方案: tech_implementation.md
  - 架构设计:
    - 系统架构设计: arch/BlueV_Architecture_Design.md
    - 实施路线图: arch/Implementation_Roadmap.md
    - 节点系统实现: arch/Node_System_Implementation.md
    - 实时通信设计: arch/Real_Time_Communication.md
    - 工作流引擎设计: arch/Workflow_Engine_Design.md
  - UI 设计:
    - 主界面设计规范: UI_Design/MainUI_Design_Specification.md
    - 节点编辑器设计: UI_Design/NodeEditor_Design_specifcation.md
    - 节点UI设计规范: UI_Design/NodeUI_Design_Specification.md
  - 开发指南:
    - 最佳实践: development/best-practices.md
    - DevOps 检查清单: development/devops-checklist.md
    - DevOps 指南: development/devops-guide.md
    - DevOps 实施计划: development/devops-implementation-plan.md
    - 项目状态: development/project-status.md
    - 故障排除: development/troubleshooting.md
  - CI/CD 状态:
    - 构建状态报告: CI_CD_STATUS_REPORT.md
    - GitHub Pages 设置: GITHUB_PAGES_SETUP.md
